spring:
  redis:
    database: 0    #redis的默认数据库为0
    host: 127.0.0.1  #链接redis的ip
    port: 6379  #链接redis的端口号
    password: 123456
    jedis:
      pool:
        max-active: 100  #链接redis的最大
        max-idle: 8      #最大的链接数量
        min-idle: 5     #最小的链接数量
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: lc
    password: lc123
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
# 七牛云存储
oss:
  qiniu:
    # 访问域名(默认使用七牛云测试域名)
    domain: http://qg2fo3psn.hn-bkt.clouddn.com
    # 公钥
    accessKey: pKD4uXE6u_ZORVhjocQ-uwGpeMiQRj7aDSus0Ujc
    # 私钥
    secretKey: DNJ6matspAFZuzKpMTZUTdSovjoOXJtajOI63Y_-
    #存储空间名称
    bucketName: luospace
upload:
  path: /fileSpace/