server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8002
spring:
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
      enabled: true
#mybatis
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: id_worker
      table-underline: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*.xml
  typeAliasesPackage: lc.*.entity
  type-aliases-super-type: java.lang.Object
logging:
  level.io.bmdata: debug
